# Generated by Django 6.0 on 2025-12-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EWasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Television', 'Television'), ('Battery', 'Battery'), ('Other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up')], default='Pending', max_length=20)),
            ],
        ),
    ]
